FROM pytorch/pytorch:nightly-devel-cuda10.0-cudnn7

RUN apt-get update && apt-get install -y --no-install-recommends \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender-dev

RUN git clone https://github.com/NVIDIA/apex && \
    cd apex && \
    pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./

RUN pip install toolz pytorch-ignite torchvision pandas fire tensorboardx scikit-learn yacs

WORKDIR /workspace
CMD /bin/bash